# Generated by Django 3.1.6 on 2021-02-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='created_by_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.addclient'),
        ),
    ]
